down:
	docker-compose down --remove-orphans
shell:
	docker exec -it spring-app_spring-app_1 /bin/sh  
up:
	docker-compose up --build --remove-orphans -d
up-f:
	docker-compose up --build --remove-orphans